version: '2'
services:
  webpython:
    build:
      context: ./
      dockerfile: server-python/docker/Dockerfile
    command: python -u app.py
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - ./server-python/code:/todo
    links:
      - rabbit
      - db
  webnginx:
    build:
      context: ./
      dockerfile: server-php/docker/server/server-nginx.docker
    volumes_from:
      - appphp
    ports:
      - "8081:80"
    links:
      - appphp
  appphp:
    build:
      context: ./
      dockerfile: server-php/docker/php/app-php-5.6.docker
    depends_on:
      - rabbit
    volumes:
      - ./server-php/code:/var/www
    links:
      - rabbit
      - db
  worker-1:
    build:
      context: ./
      dockerfile: workers/docker/Dockerfile
    command: python -u worker.py
    depends_on:
      - rabbit
      - db
    volumes:
      - ./workers/code:/todo
    links:
      - rabbit
      - db
  worker-2:
    build:
      context: ./
      dockerfile: workers/docker/SparkDockerfile
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    depends_on:
      - rabbit
      - db
    volumes:
      - ./workers/code:/todo
    links:
      - rabbit
      - db
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
  db:
    image: mongo:3.0.2
    ports:
      - "27017:27017"